spring:
  application:
    name: REVIEW-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3307/Hotel?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "" # فاضي = no password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: mh8391802@gmail.com
    password: uncz ejql elgz tjdo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

