spring:
  application:
    name: API-GATEWAY # يفضل تكون capital letters مع dashes

  cloud:
    gateway:
      routes:
        # User Service
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        # Room Service (بدل ReviewService حسب الـ modules بتاعتك)
        - id: room-service
          uri: lb://ROOM-SERVICE
          predicates:
            - Path=/api/rooms/**
          filters:
            - StripPrefix=1
        # Booking Service
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=1

        # Payment Service
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1

        # Notification Service
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
      # //http://hotelmanagement-eureka-service-1:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
